version: "3"
services:
  tileserver:
    image: maptiler/tileserver-gl-light
    container_name: tileserver
    ports:
      - "8081:8080"
    volumes:
      - ./data/madagascar_antananarivo.mbtiles:/data/madagascar_antananarivo.mbtiles
